# Generated by Django 2.0.3 on 2018-03-21 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PossibleAnswers',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='possibleanswers',
            name='questions_possible_answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Questions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='which_questions_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Questions'),
        ),
    ]
